export const curators = [
  {
    id: "amara-voss",
    name: "Amara Voss",
    initials: "AV",
    role: "Founding curator · material practice",
    city: "Brooklyn, NY",
    bio: "Amara builds exhibitions around material memory, domestic architecture, and the things a room remembers after people leave it.",
    thesis: "I look for work that changes its atmosphere when you live beside it—something that keeps revealing how it was made.",
    accent: "cobalt",
    rooms: ["East stair", "Room 204"],
    joined: "Founding season"
  },
  {
    id: "niko-halberg",
    name: "Niko Halberg",
    initials: "NH",
    role: "Digital art curator · systems & light",
    city: "New York, NY",
    bio: "Niko works with artists using code, simulation, moving image, and networked performance as their native materials.",
    thesis: "A digital work should have a life beyond the marketplace window. I sponsor systems with behavior, duration, and a preservation plan.",
    accent: "ice",
    rooms: ["Online salon", "Auditorium projection"],
    joined: "Founding season"
  },
  {
    id: "selene-park",
    name: "Selene Park",
    initials: "SP",
    role: "Independent curator · image & edition",
    city: "Queens, NY",
    bio: "Selene develops artist-led editions and intimate shows that connect print, photography, textiles, and time-based media.",
    thesis: "An edition can widen access without flattening the work. The artist’s logic for scale and supply has to remain visible.",
    accent: "coral",
    rooms: ["Library wall", "Online salon"],
    joined: "Founding season"
  },
  {
    id: "omari-bell",
    name: "Omari Bell",
    initials: "OB",
    role: "Artist-organizer · public assembly",
    city: "Brooklyn, NY",
    bio: "Omari organizes artist-run programs, public conversations, and temporary marketplaces built around shared stewardship.",
    thesis: "A market can still feel like a gathering. I want the handoff between artist and collector to leave room for context.",
    accent: "charcoal",
    rooms: ["Auditorium", "West hall"],
    joined: "Founding season"
  }
];

export const works = [
  {
    slug: "blue-hour-nassau",
    title: "Blue Hour, Nassau",
    artist: "Lena Ortiz",
    year: "2026",
    type: "physical",
    typeLabel: "Physical work",
    medium: "Oil and cold wax on linen",
    dimensions: "48 × 36 in",
    location: "Room 204 · north wall",
    price: "$4,800",
    cryptoPrice: "4,800 USDC",
    availability: "Available at launch",
    edition: "Unique work",
    chain: null,
    tokenStandard: null,
    contractStatus: null,
    curatorId: "amara-voss",
    collection: "Rooms with Weather",
    sheet: "physical",
    x: 0,
    y: 0,
    alt: "Cobalt and white gestural oil painting",
    description: "A dense blue field crossed by broad white gestures, painted over several winters in Ortiz’s Greenpoint studio. The surface moves between weather map, erased writing, and a window catching late light.",
    artistBio: "Lena Ortiz is a Brooklyn-based painter whose layered surfaces study the visual memory of streets, rooms, and changing weather.",
    curatorNote: "The painting holds its scale without raising its voice. In Room 204, the blue shifts almost hourly as north light moves across the waxed surface.",
    rights: "Purchase transfers the physical artwork only. Copyright and reproduction rights remain with the artist.",
    fulfillment: "Complimentary pickup at The School. Insured domestic shipping is quoted after purchase.",
    featured: true
  },
  {
    slug: "soft-body-study-ii",
    title: "Soft Body / Study II",
    artist: "Theo Nwosu",
    year: "2025",
    type: "physical",
    typeLabel: "Physical work",
    medium: "Cast bio-resin and pigment",
    dimensions: "22 × 20 × 7 in",
    location: "East stair · second landing",
    price: "$3,200",
    cryptoPrice: "3,200 USDC",
    availability: "Available at launch",
    edition: "Unique work",
    chain: null,
    tokenStandard: null,
    contractStatus: null,
    curatorId: "amara-voss",
    collection: "Rooms with Weather",
    sheet: "physical",
    x: 1,
    y: 0,
    alt: "Translucent cloudlike blue resin wall sculpture",
    description: "A translucent wall form assembled from thin cast membranes. Its overlapping edges hold daylight, making the object appear to swell and recede as a viewer passes.",
    artistBio: "Theo Nwosu makes sculptures about permeability, using cast skins, plant fibers, and light-responsive materials.",
    curatorNote: "Nwosu makes solidity feel temporary. The stairwell gives this work the changing sightlines it needs.",
    rights: "Purchase transfers the physical sculpture only. Copyright and reproduction rights remain with the artist.",
    fulfillment: "Pickup is preferred. Custom crating and insured shipping are available by quote.",
    featured: false
  },
  {
    slug: "common-signal",
    title: "Common Signal",
    artist: "Mara Kwon",
    year: "2026",
    type: "physical",
    typeLabel: "Physical work",
    medium: "Handwoven wool, linen, and dye",
    dimensions: "40 × 34 in",
    location: "Library wall",
    price: "$2,400",
    cryptoPrice: "2,400 USDC",
    availability: "Available at launch",
    edition: "Unique work",
    chain: null,
    tokenStandard: null,
    contractStatus: null,
    curatorId: "selene-park",
    collection: "Useful Signals",
    sheet: "physical",
    x: 2,
    y: 0,
    alt: "Brick red and ultramarine geometric textile",
    description: "A handwoven field built from repeated interruptions: a small shift in thread, a narrow line of white, a pattern that nearly becomes a letter.",
    artistBio: "Mara Kwon is a textile artist and educator working between traditional weaving structures and compressed visual language.",
    curatorNote: "This is an edition of time rather than copies—every change in rhythm records a decision made at the loom.",
    rights: "Purchase transfers the physical textile only. Copyright and reproduction rights remain with the artist.",
    fulfillment: "Pickup at The School or insured domestic shipping in an archival tube.",
    featured: false
  },
  {
    slug: "aperture-vessel",
    title: "Aperture Vessel",
    artist: "Eli Eyo",
    year: "2025",
    type: "physical",
    typeLabel: "Physical work",
    medium: "Hand-blown glass",
    dimensions: "14 × 13 × 11 in",
    location: "West hall vitrine",
    price: "$1,800",
    cryptoPrice: "1,800 USDC",
    availability: "Available at launch",
    edition: "Unique work",
    chain: null,
    tokenStandard: null,
    contractStatus: null,
    curatorId: "omari-bell",
    collection: "Assembly of Light",
    sheet: "physical",
    x: 0,
    y: 1,
    alt: "Icy cyan sculptural blown-glass vessel",
    description: "A vessel folded inward while hot, leaving a continuous interior channel that catches and bends the room around it.",
    artistBio: "Eli Eyo works in blown glass and sound, treating resonance and transparency as forms of public space.",
    curatorNote: "It is generous from every angle. The work becomes a small gathering point instead of an object with one correct front.",
    rights: "Purchase transfers the physical glass work only. Copyright and reproduction rights remain with the artist.",
    fulfillment: "Pickup is recommended. White-glove delivery is available within New York City.",
    featured: false
  },
  {
    slug: "cloud-protocol-i",
    title: "Cloud Protocol I",
    artist: "Imani Vale",
    year: "2026",
    type: "digital",
    typeLabel: "Born-digital edition",
    medium: "Generative WebGL artwork",
    dimensions: "Responsive, 4K master",
    location: "Online salon · auditorium projection",
    price: "$1,250",
    cryptoPrice: "1,250 USDC",
    availability: "Mint opens September 12",
    edition: "Edition of 20 · not yet minted",
    chain: "Base",
    tokenStandard: "ERC-1155",
    contractStatus: "Launch contract pending audit and verification",
    curatorId: "niko-halberg",
    collection: "Native Light",
    sheet: "digital",
    x: 0,
    y: 0,
    alt: "Luminous procedural cloud lattice in pale cyan",
    description: "A browser-native sky system that continually rebuilds a delicate lattice from live atmospheric inputs. Every edition shares the same rules while unfolding into a different weather history.",
    artistBio: "Imani Vale is a digital artist and creative coder working with simulated weather, collective systems, and long-duration browser works.",
    curatorNote: "The work’s subject is not clouds but agreement: small points finding a structure together, then releasing it.",
    rights: "The NFT records ownership of one edition and grants personal display rights. Copyright, commercial use, and source-code rights remain with the artist.",
    fulfillment: "Collector receives the token, a durable 4K render, and access to the live browser work. Final media permanence plan is required before mint.",
    featured: true
  },
  {
    slug: "portal-study",
    title: "Portal Study",
    artist: "Min Seo",
    year: "2026",
    type: "digital",
    typeLabel: "Born-digital 1/1",
    medium: "Real-time 3D environment",
    dimensions: "Open duration, 4K output",
    location: "Online salon",
    price: "$6,400",
    cryptoPrice: "6,400 USDC",
    availability: "Acquisition opens at launch",
    edition: "One of one · not yet minted",
    chain: "Base",
    tokenStandard: "ERC-721",
    contractStatus: "Launch contract pending audit and verification",
    curatorId: "niko-halberg",
    collection: "Native Light",
    sheet: "digital",
    x: 1,
    y: 0,
    alt: "Pixelated cobalt architectural arches dissolving into light",
    description: "An explorable sequence of cobalt arches that reconstructs itself around a viewer’s pace. No path repeats exactly; the work stores only a sparse record of where attention lingered.",
    artistBio: "Min Seo builds real-time digital spaces about attention, architecture, and the unstable boundary between memory and rendering.",
    curatorNote: "Portal Study is resolutely native to the screen, yet it understands architecture as bodily experience: rhythm, approach, pause, and threshold.",
    rights: "The NFT records ownership of the 1/1 artwork and grants personal exhibition rights. Copyright and commercial rights remain with the artist.",
    fulfillment: "Collector receives the token, archival executable, source escrow terms, and installation documentation after contract and storage verification.",
    featured: true
  },
  {
    slug: "orbit-32",
    title: "Orbit / 32",
    artist: "Yara N’Diaye",
    year: "2026",
    type: "digital",
    typeLabel: "Born-digital edition",
    medium: "Generative line system",
    dimensions: "Variable, SVG and live script",
    location: "Online salon",
    price: "$420",
    cryptoPrice: "420 USDC",
    availability: "Mint opens September 12",
    edition: "Edition of 32 · not yet minted",
    chain: "Base",
    tokenStandard: "ERC-1155",
    contractStatus: "Launch contract pending audit and verification",
    curatorId: "selene-park",
    collection: "Useful Signals",
    sheet: "digital",
    x: 2,
    y: 0,
    alt: "Restrained generative line field with a coral orbit",
    description: "Thirty-two lines negotiate the gravity of a single coral point. Each mint locks a different starting arrangement while preserving the same slow orbital behavior.",
    artistBio: "Yara N’Diaye uses code, notation, and plotter drawing to study coordination and refusal.",
    curatorNote: "The edition size is embedded in the work’s logic. Supply is not decoration; it is the system’s cast of characters.",
    rights: "The NFT records ownership of one edition and grants personal display and print rights. Copyright and commercial rights remain with the artist.",
    fulfillment: "Collector receives the token, live artwork, and a signed archival pigment print claimable within 90 days.",
    featured: false
  },
  {
    slug: "lumen-skin",
    title: "Lumen Skin",
    artist: "Ari Sol",
    year: "2026",
    type: "digital",
    typeLabel: "Born-digital 1/1",
    medium: "Procedural 3D sculpture",
    dimensions: "Loop, 06:40 min",
    location: "Auditorium projection",
    price: "$3,900",
    cryptoPrice: "3,900 USDC",
    availability: "Acquisition opens at launch",
    edition: "One of one · not yet minted",
    chain: "Base",
    tokenStandard: "ERC-721",
    contractStatus: "Launch contract pending audit and verification",
    curatorId: "niko-halberg",
    collection: "Native Light",
    sheet: "digital",
    x: 0,
    y: 1,
    alt: "Pearlescent abstract liquid-chrome digital form",
    description: "A simulated surface that repeatedly learns and loses its own edges, rendered as an endless six-minute breathing cycle.",
    artistBio: "Ari Sol creates procedural moving-image works about synthetic matter, opacity, and bodily inference.",
    curatorNote: "It never turns into a recognizable body, but it keeps borrowing the gestures of one. That tension gives the loop its staying power.",
    rights: "The NFT records ownership of the 1/1 artwork and grants personal exhibition rights. Copyright and commercial rights remain with the artist.",
    fulfillment: "Collector receives the token, lossless 4K master, display edition, and preservation documentation after storage verification.",
    featured: false
  },
  {
    slug: "stairwell-for-nobody",
    title: "Stairwell for Nobody",
    artist: "Ana Petrescu",
    year: "2026",
    type: "paired",
    typeLabel: "Physical + NFT pair",
    medium: "Graphite on paper with time-based digital twin",
    dimensions: "30 × 24 in · 05:12 min loop",
    location: "East stair · third landing / online",
    price: "$6,800",
    cryptoPrice: "6,800 USDC",
    availability: "Available as one inseparable pair",
    edition: "Unique physical work + 1/1 token · not yet minted",
    chain: "Base",
    tokenStandard: "ERC-721",
    contractStatus: "Paired-transfer contract pending audit and verification",
    curatorId: "amara-voss",
    collection: "Rooms with Weather",
    sheet: "physical",
    x: 1,
    y: 1,
    alt: "Charcoal drawing of architectural stairs with a small red mark",
    description: "A graphite stair rises toward a mark too small to be a door. Its digital twin slowly clears and rebuilds the architecture from scanned paper fibers.",
    artistBio: "Ana Petrescu moves between drawing and real-time image systems, using repetition to test where an object ends and its record begins.",
    curatorNote: "The pair is one work in two tempos: paper holds the artist’s pressure; the screen holds the drawing’s duration.",
    rights: "Physical work and NFT must transfer together. Token ownership does not convey copyright, commercial rights, or the right to separate and resell either component.",
    fulfillment: "The physical work is held when acquisition begins and released only after authoritative payment or mint confirmation. Insured shipping follows.",
    featured: true
  },
  {
    slug: "grid-chorus",
    title: "Grid Chorus",
    artist: "Joan Iles",
    year: "2026",
    type: "paired",
    typeLabel: "Physical + NFT pair",
    medium: "Glazed ceramic relief with generative sound edition",
    dimensions: "36 × 36 in · responsive audio",
    location: "West hall / online",
    price: "$5,400",
    cryptoPrice: "5,400 USDC",
    availability: "Available as one inseparable pair",
    edition: "Unique physical work + 1/1 token · not yet minted",
    chain: "Base",
    tokenStandard: "ERC-721",
    contractStatus: "Paired-transfer contract pending audit and verification",
    curatorId: "omari-bell",
    collection: "Assembly of Light",
    sheet: "physical",
    x: 2,
    y: 1,
    alt: "Pearl-white ceramic relief made from small pixel-like tiles",
    description: "A ceramic field of hand-pressed modules, accompanied by a browser work that translates the relief’s shadow pattern into a low, shifting chorus.",
    artistBio: "Joan Iles makes modular sculpture and sound systems that turn small material differences into collective behavior.",
    curatorNote: "This pair does not treat the token as a receipt. The digital work listens to the relief; each component changes how the other is understood.",
    rights: "Physical work and NFT must transfer together. Copyright, source code, and commercial rights remain with the artist.",
    fulfillment: "New York delivery and installation are included. The token transfers only after the physical installation appointment is confirmed.",
    featured: false
  }
];

export const exhibitions = [
  {
    id: "rooms-with-weather",
    title: "Rooms with Weather",
    curatorId: "amara-voss",
    kind: "In the building",
    description: "Works that change with the School’s windows, stairs, and passing bodies.",
    workSlugs: ["blue-hour-nassau", "soft-body-study-ii", "stairwell-for-nobody"]
  },
  {
    id: "native-light",
    title: "Native Light",
    curatorId: "niko-halberg",
    kind: "Born digital",
    description: "Art made to behave on-screen—not documentation of something elsewhere.",
    workSlugs: ["cloud-protocol-i", "portal-study", "lumen-skin"]
  },
  {
    id: "assembly-of-light",
    title: "Assembly of Light",
    curatorId: "omari-bell",
    kind: "September bazaar",
    description: "Objects, projections, and sounds that make a temporary public out of a room.",
    workSlugs: ["aperture-vessel", "grid-chorus", "orbit-32"]
  }
];

export const discoveries = [
  { id: "d-cloud", workSlug: "cloud-protocol-i", from: "Niko", when: "Today", status: "new", source: "Direct link" },
  { id: "d-soft", workSlug: "soft-body-study-ii", from: "Amara", when: "Today", status: "new", source: "Studio visit" },
  { id: "d-orbit", workSlug: "orbit-32", from: "Selene", when: "Yesterday", status: "saved", source: "Direct link" },
  { id: "d-grid", workSlug: "grid-chorus", from: "Omari", when: "Yesterday", status: "new", source: "Bazaar" },
  { id: "d-lumen", workSlug: "lumen-skin", from: "Niko", when: "Aug 20", status: "sponsored", source: "Artist intro" },
  { id: "d-common", workSlug: "common-signal", from: "Selene", when: "Aug 19", status: "new", source: "Studio visit" }
];

export const bazaar = {
  title: "Assembly of Light",
  date: "2026-09-12T12:00:00-04:00",
  dateLabel: "Saturday, September 12",
  timeLabel: "12–7 PM",
  location: "The School auditorium · 29 Nassau Avenue",
  hostCuratorId: "omari-bell",
  description: "The School’s monthly in-person market brings physical work, live digital editions, curator conversations, and an all-day projection salon into one room.",
  schedule: [
    { time: "12:00", title: "Doors open", note: "Preview the floor and projection salon" },
    { time: "1:30", title: "Curator walk", note: "Omari Bell on Assembly of Light" },
    { time: "3:00", title: "Digital works, durable lives", note: "Artist conversation and preservation demo" },
    { time: "5:00", title: "Live edition window", note: "Guided wallet and card acquisition support" },
    { time: "6:30", title: "Closing assembly", note: "Final walkthrough; no auction countdown" }
  ],
  exhibitors: ["Eli Eyo", "Joan Iles", "Imani Vale", "Yara N’Diaye", "Mara Kwon", "Theo Nwosu"]
};

export const getCurator = (id) => curators.find((curator) => curator.id === id);
export const getWork = (slug) => works.find((work) => work.slug === slug);
export const getExhibition = (id) => exhibitions.find((exhibition) => exhibition.id === id);
export const worksForCurator = (id) => works.filter((work) => work.curatorId === id);
